[package]
name = "rpo-xhash-m31"
version = "0.1.0"
edition = "2024"

[dependencies]
digest = "0.10.7"
once_cell = "1.21.3"
rand = "0.9.1"
sha3 = "0.10.8"
stwo-prover = { git = "https://github.com/starkware-libs/stwo", rev = "19d12d7", default-features = false }
tinyvec = "1.9.0"
